[variables]
NIXPACKS_BUN_VERSION = "1.3.13"

[phases.setup]
nixpkgsArchive = '73c703c22422b8951895a960959dbbaca7296492#bun'

[phases.install]
cmds = ["bun i"]

[phases.build]
cmds = ["bun run --filter @workspace/api build"]

[start]
cmd = "bun run --filter @workspace/api start"
