import { baseTemplate, btn, cardSection, divider, h1, infoBox, muted, p } from "./base.js";

export interface RepPortalTemplateProps {
  repName: string;
  /** The workspace/company name */
  workspaceName: string;
  /** Full portal URL, e.g. https://app.commissionkit.io/portal/abc123 */
  portalUrl: string;
  /** The unique username for logging in */
  portalUsername: string;
  /** Optional portal password */
  portalPassword?: string;
}

export function repPortalTemplate(props: RepPortalTemplateProps): string {
  const { repName, workspaceName, portalUrl, portalUsername } = props;

  const body = `
    ${h1("Your commission portal is ready 🎉")}
    ${p(`Hi ${repName},`)}
    ${p(`<strong>${workspaceName}</strong> has set up a personalised commission portal for you. You can securely view your earnings, deal breakdowns, and historical payouts at any time.`)}

    ${btn(portalUrl, "View My Commission Portal")}

    ${infoBox(`Bookmark this link — it's your personal portal and is always up to date with your latest commissions.`)}

    ${cardSection(`
      <table width="100%" cellpadding="0" cellspacing="0" class="ck-stack">
        <tr>
          <td>
            <p style="margin:0 0 4px;font-size:12px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;">Your username</p>
            <p style="margin:0;font-size:18px;font-family:monospace;color:#111827;letter-spacing:1px;font-weight:700;">${portalUsername}</p>
          </td>
          ${
            props.portalPassword
              ? `
          <td style="text-align:right;">
            <p style="margin:0 0 4px;font-size:12px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;">Your password</p>
            <p style="margin:0;font-size:18px;font-family:monospace;color:#111827;font-weight:700;">${props.portalPassword}</p>
          </td>
          `
              : ""
          }
        </tr>
      </table>
      <p style="margin:12px 0 0;font-size:12px;color:#6B7280;">Keep these credentials secure. You will need them to access your portal.</p>
    `)}

    ${divider()}
    ${muted("If you weren't expecting this email, you can safely ignore it. This link was generated by your sales manager.")}
  `;

  return baseTemplate({
    previewText: `${workspaceName} has shared your commission portal — view your earnings`,
    body,
    footerNote: `This email was sent on behalf of ${workspaceName} via CommissionKit.`,
  });
}
