// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/commission-variants/AlmondStyle.tsx": () => import("../components/mockups/commission-variants/AlmondStyle.tsx"),
  "./components/mockups/commission-variants/SlateSage.tsx": () => import("../components/mockups/commission-variants/SlateSage.tsx"),
  "./components/mockups/commission-variants/TwilightDark.tsx": () => import("../components/mockups/commission-variants/TwilightDark.tsx"),
  "./components/mockups/commission-variants/WarmSand.tsx": () => import("../components/mockups/commission-variants/WarmSand.tsx"),
  "./components/mockups/logos/LogoA.tsx": () => import("../components/mockups/logos/LogoA.tsx"),
  "./components/mockups/logos/LogoB.tsx": () => import("../components/mockups/logos/LogoB.tsx"),
  "./components/mockups/logos/LogoC.tsx": () => import("../components/mockups/logos/LogoC.tsx")
};
