// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/commission-variants/SlateSage.tsx": () => import("../components/mockups/commission-variants/SlateSage.tsx"),
  "./components/mockups/commission-variants/TwilightDark.tsx": () => import("../components/mockups/commission-variants/TwilightDark.tsx"),
  "./components/mockups/commission-variants/WarmSand.tsx": () => import("../components/mockups/commission-variants/WarmSand.tsx")
};
